INSERT INTO STUDENT VALUES(1,19,'Digaant Garg');
INSERT INTO STUDENT VALUES(2,19,'Ganesh Madarasu');
INSERT INTO STUDENT VALUES(3,19,'Kirat Alang');
INSERT INTO STUDENT VALUES(4,19,'Pranjal Jain');

INSERT INTO TEST VALUES(1,'Geometry','A',1);
INSERT INTO TEST VALUES(2,'Geography','B+',1);
INSERT INTO TEST VALUES(3,'Geometry','C',2);
INSERT INTO TEST VALUES(4,'Geography','B',2);
INSERT INTO TEST VALUES(5,'Geometry','A',3);
INSERT INTO TEST VALUES(6,'Geography','A',3);
INSERT INTO TEST VALUES(7,'Geometry','B',4);
INSERT INTO TEST VALUES(8,'Geography','C+',4);
INSERT INTO TEST VALUES(9,'English','C+',1);
INSERT INTO TEST VALUES(10,'English','B+',2);
INSERT INTO TEST VALUES(11,'English','B',3);
