INSERT INTO STUDENT VALUES(1,19,'Digaant Garg');
INSERT INTO STUDENT VALUES(2,19,'Ganesh Madarasu');
INSERT INTO STUDENT VALUES(3,19,'Kirat Alang');
INSERT INTO STUDENT VALUES(4,19,'Pranjal Jain');


